/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myowndictionary;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.border.BevelBorder;
/**
 *
 * @author Trykson
 */
public class MyOwnDictionary extends javax.swing.JFrame {
    
    static String username, password, addres, port,databaseName;

   static public void setUsername(String username) {
        MyOwnDictionary.username = username;
    }

   static public void setPassword(String password) {
        MyOwnDictionary.password = password;
    }


   static public void setAddres(String addres) {
        MyOwnDictionary.addres = addres;
    }

   static public void setPort(String port) {
        MyOwnDictionary.port = port;
    }

   static public void setDatabaseName(String databaseName) {
        MyOwnDictionary.databaseName = databaseName;
    }
  Connection con;
    Statement stmt;
    String SQL = "SELECT * FROM Workers";
    ResultSet rs;
    /**
     * Creates new form MyOwnDictionary
     */
    public MyOwnDictionary() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBloggin = new javax.swing.JButton();
        jTextID = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBloggin.setText("Login");
        jBloggin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBlogginActionPerformed(evt);
            }
        });

        jTextID.setText("ID");

        jMenu2.setText("Options");

        jMenuItem3.setText("Sign in");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jBloggin, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(jTextID, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jBloggin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     public void DoConnect() {
        try {

            String host;
            host = "jdbc:derby://"+addres+":"+port+"/"+databaseName;
            
            con = DriverManager.getConnection(host, username, password);
           

            stmt = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);

            rs = stmt.executeQuery(SQL);

            rs.next();
            Integer idint;
            idint = rs.getInt("ID");
            
            jTextID.setText(Integer.toString(idint));
           

        } catch (SQLException ex) {
            Logger.getLogger(MyOwnDictionary.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
//         JFrame frame = new JFrame("Popup Menu Example");
//
//           frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
//    frame.setSize(300, 300);
//    frame.setVisible(true);

LoginWindow lw = new LoginWindow();
lw.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jBlogginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBlogginActionPerformed
        // TODO add your handling code here:
//            addres = jTextServer.getText();
//            port = jTextPort.getText();
//            databaseName = jTextDatabaseName.getText();
//            
//            host = "jdbc:derby://"+addres+":"+port+"/"+databaseName;
//        
//          username  = jTextFieldUsername.getText();
//          password = jPassField.getText();
          DoConnect();
            
        
    }//GEN-LAST:event_jBlogginActionPerformed

   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyOwnDictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyOwnDictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyOwnDictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyOwnDictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyOwnDictionary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBloggin;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JTextField jTextID;
    // End of variables declaration//GEN-END:variables
}
